server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
        grpc:

compactor:
  compaction:
    block_retention: 48h                # configure total trace retention here

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: linux-microservices
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://admin:password@prometheus:9090/api/v1/write    # if you use as part of Docker Compose, use this line.
      # - url: http://admin:password@localhost:9090/api/v1/write   # if you run locally, use this line.
        send_exemplars: true

storage:
  trace:
    backend: local                
    local:
      path: /tmp/tempo/traces      # Set to correct path on your computer
    wal:
      path: /tmp/tempo/wal         # Set to correct path on your computer

#storage:
#  trace:
#    backend: s3                 
#    s3:
#      bucket: your-s3-bucket-name
#      region: your-region
#      access_key: your-access-key  # not needed if role_arn is used.
#      secret_key: your-secret-key  # not needed if role_arn is used.
#      role_arn: arn:aws:iam::123456789012:role/your-tempo-role

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]
